name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - first-page

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Astro
        run: npm run build

      - name: Subir archivos de GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v1